src/pivotal-ui/components/iconography/iconography.scss
src/pivotal-ui/components/iconography/package.json

fix(iconography): Add line height to fa-h1 through fa-h6

---

hologram/doc_assets/_header.html
src/pivotal-ui/components/hiring/package.json
src/pivotal-ui/components/hiring/product_designer.scss
src/pivotal-ui/components/intro/intro.scss

Add Product designer job posting that links to jobvites for application.
[#97262154]

feat(styleguide): Add product designer job req

---

tasks/vendor-package.js

Doing it live!
This is a hotfix for an eslint violation. Not really sure if it's the right fix or not, but it seems safe to do...
Check it out @gpleiss and Matt!
- pm & sh

fix(vendor-package): temp fix for ci error

---

src/pivotal-ui-react/notifications/notifications.js

fix(notifications): Fix h2 styling on AlertNotification component.

---

src/pivotal-ui/components/dropdowns/dropdowns.scss

fix(dropdowns): Remove unneeded notifications CSS

---

src/pivotal-ui/components/modals/modals.scss

feat(modals) Remove alt modal

---

src/pivotal-ui/components/collapse/collapse.scss

feat(collapse) Removes large accordion

---

spec/pivotal-ui-react/radio/radio_spec.js
src/pivotal-ui-react/radio/radio.js

feat(radio): Classname and style passes through to radio div

---

spec/pivotal-ui-react/media/media_spec.js
src/pivotal-ui-react/media/media.js
src/pivotal-ui/components/media/media.scss

Added spec tests for flag and media for className, innerClassName, id,
and style passthrough.
Added innerClassName to scss documentation.
[Finishes #98913330]

fix(media): InnerClassName passes through to the media-body

---

spec/pivotal-ui-react/modals/modals_spec.js
src/pivotal-ui-react/modals/modals.js
src/pivotal-ui/components/modals/modals.scss

modal, modalBody, and modalFooter passthrough these attributes
[Finishes #98913332]

feat(modal): Modals passthrough className, id, and style

---

src/pivotal-ui/components/code/code.scss

- Instructions for stylized code and terminal window only
- Includes installation instructions for `pui-prismjs` package
- Includes list of themes to install

Add special installation instructions for stylized code component

---

spec/pivotal-ui-react/panels/panels_spec.js
src/pivotal-ui-react/panels/panels.js
src/pivotal-ui/components/panels/panels.scss

className, id, and style passthrough to the panel and
innerClassName, innerId, and innerStyle passthrough to the panel-body
[Finishes #98986988]

feat(panels): Adds passthroughs for className, id, and style

---

spec/pivotal-ui-react/draggable-list/draggable-list_spec.js
src/pivotal-ui-react/draggable-list/draggable-list.js
src/pivotal-ui/components/lists/lists.scss

Draggable list passes through className, style, and id to ul
and passes innerClassName to list items.
Updated Documentation
[Finishes #98913256]

feat(draggable-list): Draggable list passes through attributes

---

spec/pivotal-ui-react/divider/divider_spec.js
spec/pivotal-ui-react/draggable-list/draggable-list_spec.js
spec/pivotal-ui-react/grids/grid_spec.js
spec/pivotal-ui-react/iconography/iconography_spec.js
spec/pivotal-ui-react/image/image_spec.js
spec/pivotal-ui-react/lists/lists_spec.js
spec/pivotal-ui-react/search-input/search-input_spec.js
spec/pivotal-ui-react/spec_helper.js
spec/pivotal-ui-react/support/shared_examples.js
spec/pivotal-ui-react/typography/typography_spec.js

Adds tests for this functionaliy.
[Finishes #98913326]

fix(lists) List passthroughs className, id, and style

---

package.json
spec/pivotal-ui-react/tooltip/tooltip_spec.js
src/pivotal-ui-react/alerts/package.json
src/pivotal-ui-react/collapse/package.json
src/pivotal-ui-react/dropdowns/package.json
src/pivotal-ui-react/grids/package.json
src/pivotal-ui-react/overlay-trigger/package.json
src/pivotal-ui-react/tabs/package.json
src/pivotal-ui-react/tooltip/package.json

- Upgrade to latest version of React Bootstrap
[Finishes #98913250]

feat(tooltip): Adds className, id, and style passthrough

---

spec/pivotal-ui-react/dropdown/dropdown_spec.js
spec/pivotal-ui-react/notification/notification_spec.js
src/pivotal-ui-react/notifications/notifications.js
src/pivotal-ui-react/notifications/package.json
src/pivotal-ui/components/dropdowns/dropdowns.scss

Notification follows dropdown semantics for passing through these
attributes.
[Finishes #98913374]

feat(notification): Notifications pass through className, style, and id

---

src/pivotal-ui/components/typography/typography.scss

Simply adding the modifiers to the big color class table.
---
Add color modifiers to the table of all the color classes to the
styleguide.
[#99441746]

Add Dark Type Modifiers to Documentation

---

spec/pivotal-ui-react/buttons/button_spec.js
src/pivotal-ui/components/buttons/buttons.scss
src/pivotal-ui/components/mixins.scss
src/pivotal-ui/components/pui-variables.scss

BREAKING CHANGE: (css class): Removes btn-primary
Signed-off-by: Kenny Wang <kwang@pivotal.io>

fix(buttons): Changes style of buttons.

---

spec/pivotal-ui-react/buttons/button_spec.js
src/pivotal-ui/components/buttons/buttons.scss
src/pivotal-ui/components/dropdowns/dropdowns.scss
src/pivotal-ui/components/mixins.scss
src/pivotal-ui/components/pui-variables.scss

Design dropdown changes

---

src/pivotal-ui/components/alerts/alerts.scss

[Finishes ##100256214]
BREAKING CHANGE: (css class) .alert-icon styles icons within alerts

fix(alerts): Alert styles changed

---

src/pivotal-ui/components/buttons/buttons.scss
src/pivotal-ui/components/forms/forms.scss
src/pivotal-ui/components/pui-variables.scss

[Finishes #100255918[
Signed-off-by: Kenny Wang <kwang@pivotal.io>

fix(selects): Changes select styling

---

package.json
spec/pivotal-ui-react/tab/tab_spec.js
src/pivotal-ui-react/tabs/package.json
src/pivotal-ui-react/tabs/tabs.js

Signed-off-by: Dominick Reinhold <dreinhold@pivotal.io>

feat(tabs): Set correct aria-controls value for Tab nav items

---

Gemfile.lock
spec/pivotal-ui-react/tab/tab_spec.js
src/pivotal-ui-react/tabs/tabs.js
src/pivotal-ui/components/tabs/tabs.scss

Version 2. Do not merge both tabs responsive PRs.
[Finishes #99800334]
Signed-off-by: Caroline Taymor <ctaymor@pivotal.io>
Signed-off-by: Geoff Pleiss <gpleiss@pivotal.io>

feat(tabs): Makes tabs responsive

---

spec/pivotal-ui-react/modals/modals_spec.js
src/pivotal-ui-react/modals/modals.js

Adds tabbing within an open modal and aria roles and states.
Signed-off-by: Kenny Wang <kwang@pivotal.io>

feat(modals): Modals are more accessible

---

src/styleguide/intro-page.js

Add examples using Pivotal UI
re: #283

chore(intro): add pui examples

---

src/pivotal-ui-react/dividers/dividers.js

Add examples using Pivotal UI.
re: #293 and [#106259852]

chore(docs): update divider docs

---

src/pivotal-ui-react/media/media.js

This confused me for a bit. I think these changes would help someone new to Flag and Media.
cc: @rochesterinnyc

Note the difference between Flag and Media

---

library/spec/pivotal-ui-react/tabs/tabs_spec.js
library/src/pivotal-ui-react/tabs/tabs.js

Tabs passthrough props

---

library/src/pivotal-ui/components/typography/typography.scss

fixes #378
Signed-off-by: Dan Dzoan <ddzoan@pivotal.io>

fix(Headers): Don't hardcode all header colors

---

library/src/pivotal-ui/components/panels/panels.scss
styleguide/docs/css/panels.scss

[#117238859]
Signed-off-by: Elena Sharma <esharma@pivotal.io>

feature(panels): Add panel loading animation

---

library/spec/pivotal-ui-react/mixins/mounted_mixin_spec.js
library/src/pivotal-ui-react/mixins/mixins/mounted_mixin.js

feature(mounted): add mounted mixin that determines when a component is mounted

Mounted Mixin

---

library/spec/pivotal-ui-react/dropdown/dropdown_spec.js
library/src/pivotal-ui-react/dropdowns/dropdowns.js

[#116913731]
Signed-off-by: William Lindner <wlindner@pivotal.io>

feat(dropdown): Support passing your own toggle onClick handler

---

library/src/pivotal-ui-react/draggable-list/draggable-list.js

DraggableList doesn´t work on IE #394

fix(DraggableList ): DraggableList fix for IE 10, 11 and Edge #394

---

library/src/pivotal-ui/components/pui-variables.scss
library/src/pivotal-ui/components/typography/typography.scss

fix(typography): include semibold and fix font-weight for bold font

---

library/src/pivotal-ui/components/modals/README.md
library/src/pivotal-ui/components/modals/modals.scss
library/src/pivotal-ui/components/pui-variables.scss
styleguide/docs/css/modals.scss

- changed background color to white
- changed header padding
- removed unnecessary .modal-basic class
- removed upper case text transform
- add box shadow

feature(modals):improved style

---

library/src/pivotal-ui-react/collapse/package.json

Signed-off-by: Lisa Cho <lcho@pivotal.io>

fix(collapse): Add collapsible dependency

---

README.md

https://github.com/pivotal-cf/pivotal-ui/issues/419

Remove frankenstyle documentation, simplify css

---

library/spec/pivotal-ui-react/inputs/inputs_spec.js
library/src/pivotal-ui-react/inputs/inputs.js
library/src/pivotal-ui/components/forms/forms.scss
styleguide/docs/react/inputs.js

Signed-off-by: Charles Hansen <chansen@pivotal.io>

feat(inputs): input accepts custom left icon

---

library/src/pivotal-ui/components/forms/forms.scss

Signed-off-by: Charles Hansen <chansen@pivotal.io>

fix(inputs): center left icons

---

COMMIT_GUIDELINES.md
CONTRIBUTING.md
CONTRIBUTING_STYLEGUIDE.md

Signed-off-by: Jean de Klerk <jadekler@gmail.com>
We spent a good amount of time reading through and walking through the `CONTRIBUTING.md`. We've attempted to streamline that file to just what someone would need to begin iterating on a component.  Necessary details on project styling and workflows have been moved to a separate `CONTRIBUTING_STYLEGUIDE.md`, and details on commit best practices have been moved into `COMMIT_GUIDELINES.md`.

Clean up and streamline CONTRIBUTING.md

---

library/src/pivotal-ui/components/dropdowns/dropdowns_mixins.scss
library/src/pivotal-ui/components/select/select.scss

Signed-off-by: Lisa Cho <lcho@pivotal.io>

Bug(dropdowns): fix dropdown styling for firefox [fixes #134458385]

---

library/spec/pivotal-ui-react/toggle/toggle_spec.js
library/src/pivotal-ui-react/toggle/toggle.js
library/src/pivotal-ui/components/forms/forms.scss
library/src/pivotal-ui/components/pui-variables.scss
styleguide/docs/react/toggle.js

Note: this removes 3 toggle related variables from pui-variables.scss
[Finishes #134017213]

feat(toggle): add 'size' attribute

---

styleguide/docs/react/panels.js

[#135045075]
Signed-off-by: Jean de Klerk <jadekler@pivotal.io>

feat(panel): Add documentation for panel props

---

library/spec/pivotal-ui-react/iconography/iconography_spec.js
library/src/pivotal-ui-react/iconography/iconography.js
library/src/pivotal-ui/components/iconography/iconography.scss
styleguide/docs/react/iconography.js

PRing to get review started, but do have an outstanding question about whether [#135989699](https://www.pivotaltracker.com/n/projects/1126018/stories/135989699) wants `verticalAlign` to exist on the `Svg` component, too.

feat(Icon): Add verticalAlign prop support [#135989699]

---

library/src/pivotal-ui/components/iconography/iconography.scss
library/src/pivotal-ui/components/iconography/spinner.scss
library/src/pivotal-ui/components/iconography/svgs/spinner-md.svg
library/src/pivotal-ui/components/iconography/svgs/spinner-sm.svg
library/src/pivotal-ui/components/iconography/svgs/spinner.svg
library/src/pivotal-ui/components/pui-variables.scss
styleguide/docs/react/iconography.js

https://www.pivotaltracker.com/n/projects/1126018/stories/130843161

feat(Iconography): Add support for spinner, spinner-md, and spinner-sm

---

library/tasks/helpers/publish-helper.js

Signed-off-by: Tom Chen <tochen@pivotal.io>
#136121835

Add tom and jean to publish helper

---

library/src/pivotal-ui/components/buttons/buttons.scss

Clear description of the line-height calculation

Updated button line-height calculations

---

library/src/pivotal-ui/components/flex-grids/flex-grids.scss

Added !important to .col-top and .col-bottom. This will close out this story.
[#140864621]

Making Flex Grid modifiers important [#140864621]

---

styleguide/docs/css/forms.scss

Added .form-group to basic forms, inline forms, and sizing inputs/selects that needed it. 
Easy part of this story.
[#140787845]

Forms Docs Fixes [#140787845]

---

styleguide/docs/css/forms.scss

Added the select icon and .form-groups to <select> elements. Finishing this story.
[#139964833]

Select Icons in Forms [#139964833]

---

library/src/pivotal-ui/components/forms/forms.scss

Fixed the absolute position of icons in forms
[#140787845]

Icon placement in forms fix

---

library/spec/pivotal-ui-react/table/flex-table_spec.js
library/src/pivotal-ui-react/table/table.js
styleguide/docs/react/table.js

This attribute will add the given class to all cells in a column.
[#142249597]
Signed-off-by: Elana Koren <ekoren@pivotal.io>

feat(table): React table columns accept cellClass

---

styleguide_new/src/components/renderers/table_renderer.js
styleguide_new/stylesheets/app.scss

Related issue:
https://github.com/pivotal-cf/pivotal-ui/issues/520

Missing dependencies in package.json for react flex grids fixed

---

src/css/forms/forms.scss

to fix this bug: https://www.pivotaltracker.com/story/show/153076986

add back input's left padding

---

sandbox/yarn.lock
yarn.lock

It has more integrity. Like George Washington.

update yarn.lock file generated from yarn 1.10.1

---

spec/pivotal-ui-react/forms/form_spec.js
src/react/forms/form.js

When clicking a checkbox in a PUI form, the `onModified` callback is not called. This PR adds that functionality.

when modifying a checkbox field, call the onModified callback

---

spec/pivotal-ui-react/flex-grids/grid_spec.js
src/css/flex-grids/flex-grids.scss
src/react/flex-grids/grid.js

Signed-off-by: Kashyap Vedurmudi <kvedurmudi@pivotal.io>

Add flexDirection prop to Grid component
