src/pivotal-ui-react/notifications/notifications.js, src/pivotal-ui/components/dropdowns/dropdowns.scss, src/pivotal-ui/components/dropdowns/package.json, src/pivotal-ui/components/pui-variables.scss, src/pivotal-ui/components/typography/typography.scss
Lots of changes here
- Typography `.h{size}` classes now are !important, which makes the following changes possible.
- Update the notifications css component so that modifiers aren't necessary anymore
- No need for size/color modifiers on the dropdown bell/badge
- No need for size/color modifiers on the "no notifications" bell
- Remove some unnecessary classes
The "legacy" way of creating notifications still works, and is marked as deprecated.
=> Improve notifications

spec/pivotal-ui-react/dropdown/dropdown_spec.js, src/pivotal-ui-react/dropdowns/dropdowns.js
React-bootstrap was adding the `btn-default` to the `DefaultAltDropdown` which was overriding styles. It was also adding that class to the `LowlightDropdown`, `HighlightDropdown`, and `HighlightAltDropdown`. This PR removes the `btn-default` class from those dropdowns.
=> Fix: Add border on hover to DefaultAltDropdown

src/pivotal-ui/components/pui-variables.scss, src/pivotal-ui/components/typography/typography.scss
This breaks a few css-critic tests, but the changes are small or non-existent on a visual inspection.
=> feat(typography): Headers now have a smaller line-height

src/pivotal-ui/components/lists/lists.scss
This PR "amends" #185.
BREAKING CHANGE: (html) The `.event-list` class is no longer supported.
If you want to build a event list, build it up using a group list. See
an example at http://styleguide.pivotal.io/elements.html#list_group
=> fix(lists): Removes event list css

src/pivotal-ui/components/lists/lists.scss
[Finishes #88969522]
BREAKING CHANGE: (css) addable list animations removed. Do not use.
=> feat(lists): remove addable list

src/pivotal-ui/components/bootstrap/package.json
bootstrap peer dependency locked down to version 3.3.5
[Finishes #98028534]
=> feat(bootstrap): lockdown peer dependency of bootstrap version

spec/pivotal-ui-react/sortable-table/sortable-table_spec.js, src/pivotal-ui-react/sortable-table/sortable-table.js, src/pivotal-ui/components/tables/tables.scss, src/pivotal-ui/javascripts/components.js
New interface for sortable-table, which also fixes the bug where the
table didn't rerender when the data changed.
[Finishes #97658788]
BREAKING CHANGE: (javascript) React component has new wrapping components for
the header and rows.
=> fix(sortable-table): refactor sortable-table to rerender with data change

spec/pivotal-ui-react/collapse/collapse_spec.js, src/pivotal-ui-react/collapse/collapse.js
Tests that className and style are passed through to the div containing
the collapse. react-bootstrap passes id to the content of the collapse.
Refactors BaseCollapse to use mergeprops.
[Finishes #98913410]
=> fix(collapse): Adds test for className and style passthrough

spec/pivotal-ui-react/dropdown/dropdown_spec.js, src/pivotal-ui-react/dropdowns/dropdowns.js, src/pivotal-ui-react/dropdowns/package.json, src/pivotal-ui/components/dropdowns/dropdowns.scss
Dropdown passes through className and style.
Dropdown merges buttonClassName when provided.
Updates documentation to include buttonClassName.
[Finishes #98913274]
=> feat(dropdown): Dropdown passes through attributes

src/pivotal-ui-react/back-to-top/back-to-top.js
- Remove `role=button`, since back-to-top is a navigating element
- Add `href=#top` so it is percieved as a link and becomes tabbable
- Add aria-label
[Finishes #100047042]
=> feat(back-to-top): improve accessibility of back-to-top

spec/features/components/expander_spec.rb, spec/features/spec_helper.rb, spec/pivotal-ui-react/expander/expander_spec.js, src/pivotal-ui-react/expander/expander.js, src/pivotal-ui-react/expander/package.json, src/pivotal-ui/components/expander/expander.scss, src/pivotal-ui/components/react-animations/react-animations.scss
Before, with large content, the expander would open smoothly for some
percentage of the distance and then suddenly jump the rest.
The expander component now has a new css dependency (`pui-css-bootstrap`). This is because the expander now relies on bootstrap's collapse animation to be less janky.
=> fix(expander): Handle expander open animation correctly

package.json, spec/pivotal-ui-react/stream-list/stream-list_spec.js, spec/task-helpers/package-version-helper-spec.js, src/pivotal-ui-react/stream-list/package.json, src/pivotal-ui-react/stream-list/stream-list.js, src/pivotal-ui/components/lists/lists.scss, src/pivotal-ui/javascripts/components.js
Some open questions we had around the API design:
1. Should ListItems appear in reversed order? I.e. does 
```jsx
<StreamList>
<ListItem>Item a</ListItem>
<ListItem>Item b</ListItem>
```
render as:
```
Item b
Item a
```
This is so that new data appears on the top of the list.
2. Should the stream list be component be a `StreamList` (i.e. a separate component than `GroupList`)? Or should the stream list be a `GroupList` with `stream={true}` (or a similar property)?
3. The text on the button: we have two props - `singularNewItemText` and `pluralNewItemsText`. So the button would say "1 {singularNewItemText}" or "4 {pluralNewItemsText}" (e.g. "1 new item", "4 new items"). If not supplied, we provide the default values of "new item"/"new items". Does this seem like a necessary/reasonable way …
=> feat(stream-list): Creates a stream-list component

src/pivotal-ui-react/alerts/alerts.js, src/pivotal-ui/components/alerts/alerts.scss
When the close button is followed by a media component, the margin
should be cleared. There is a special rule that handled this for alerts
inside a table which is how it is shown in the styleguide.
=> fix(alerts): Remove extra margin on the alert

package.json, spec/pivotal-ui-react/tab/tab_spec.js, src/pivotal-ui-react/tabs/tabs.js, src/pivotal-ui/components/tabs/tabs.scss
BREAKING CHANGE: (react) React Tab's property tab is now called title
Signed-off-by: Matt Royal <mroyal@pivotal.io>
=> feat(tabs): Upgrade to new Tabs API

src/pivotal-ui/components/links/links.scss, src/pivotal-ui/components/pui-variables.scss
Paired with Justin on this.
BREAKING CHANGE: (css class) link-lowlight-alt is no longer supported.
Please use link-lowlight instead.
=> fix(links): Updates link colors and hover/focus and active states

src/pivotal-ui/components/alerts/alerts.scss, src/pivotal-ui/components/buttons/README.md, src/pivotal-ui/components/buttons/buttons.scss, src/pivotal-ui/components/collapse/collapse.scss, src/pivotal-ui/components/labels/labels.scss, src/pivotal-ui/components/media/README.md, src/pivotal-ui/components/media/media.scss
All CSS components which are not hidden now have meaningful link text.
Signed-off-by: Caroline Taymor <ctaymor@pivotal.io>
=> feat(a11y): More CSS components have clear link text

src/pivotal-ui/components/mixins.scss
This was a duplicate mixin with font-helper in typography.scss which was
not being used internally.
[Finishes #98963152]
BREAKING CHANGE: (scss mixin): font() mixin no longer available. Use
font-helper mixin from pui-css-typography instead.
=> feat(mixin): Removed font mixin from mixins.scss

PUI_VARIABLES_AND_MIXINS_README.md
The name of npm package is `pui-css-variables-and-mixins`.
=> chore(documentation): Fix package name in UI Variables and Mixins README

src/pivotal-ui-react/overlay-trigger/package.json
Signed-off-by: Marc Magruder <questionmarcs@gmail.com>
- overlay-trigger requires the lodash.uniqueid module (which is not part of lodash) to work and this commit prevents users from having to explicitly require it.
=> Add lodash.uniqueid dependency

spec/pivotal-ui-react/draggable-list/draggable-list_spec.js, src/pivotal-ui-react/draggable-list/draggable-list.js
* callback is only called once per drag
* callback is called on dragEnd instead of drop so that it is called even
when the mouse is outside of the list
[Finishes #102532202]
Signed-off-by: Claire Thompson <cthompson@pivotal.io>
BREAKING CHANGE: DraggableList callback onDrop is no longer passed to
list items - use onDragEnd instead to provide a callback.
=> fix(draggable-list): draggable list callback is fixed

src/pivotal-ui-react/dropdowns/package.json
dropdowns also requires the lodash.uniqueid module (which is not part of lodash) to work and this commit prevents users from having to explicitly require it.
Fixes issue stated in comment here: https://github.com/pivotal-cf/pivotal-ui/pull/250
=> Add lodash.uniqueid dependency for dropdowns

src/pivotal-ui-react/autocomplete/autocomplete-input.js
fix(autocomplete): withRelatedTarget now merges properties in correct order
This fixes an issue in Firefox and Safari where clicking an Autocomplete
list item closed the list without calling the proper pick function.
This happened because the Autocomplete Input's blur function was
incorrectly making it to its last line which hides the list before that
pick function could be called. It was making it past the intended early
return condition because relatedTarget was null (except in Chrome).
relatedTarget was null because a object full of null properties
was merging on top of the actual relatedTarget in the withRelatedTarget
helper function.
[#101461670]
=> fix(autocomplete): withRelatedTarget now merges properties in correct order

src/pivotal-ui/components/typography/package.json
Pivotal-ui-charts is trying to remove font-awesome, since it doubles the size of our app. We've removed it everywhere except that it remains a subdependency of pui-css-typography which we still need. Pui-css-typography does not appear to use font-awesome so we would like to remove it.
=> fix(dependency): remove unused font-awesome dependency for pui-css-typography

library/spec/pivotal-ui-react/panels/panels_spec.js, library/src/pivotal-ui-react/panels/panels.js, library/src/pivotal-ui/components/panels/panels.scss, styleguide/docs/css/panels.scss, styleguide/docs/react/panels.js
See issue #318, #285 
Panels can receive a `title` prop that is either a string or a React Component
=> Allow Panels to have full headers

library/spec/pivotal-ui-react/autocomplete/autocomplete_spec.js, library/src/pivotal-ui-react/autocomplete/autocomplete-input.js
We noticed that the autocomplete list would close before the click event on the list item could trigger. This was because relatedTarget of the blur event in Safari doesn't work correctly - it returns the HTML body instead of the list item. If onfocusout is used instead of React's onBlur, the relatedTarget property of the event works in Safari.
Signed-off-by: Douglas Blumeyer <dblumeyer@pivotal.io>
=> fix(autocomplete): Use onfocusout instead of onBlur, for Safari support

styleguide/src/intro-page.js
Regarding: #374
Including TileLayoutItem seemed to do the trick:
`const TileLayoutItem = global.TileLayoutItem || require('pui-react-tile-layout');`
@charleshansen
=> Fix TileLayout on Styleguide Home Page

library/spec/pivotal-ui-react/dropdown/dropdown_spec.js, library/spec/pivotal-ui-react/notification/notification_spec.js, library/src/pivotal-ui-react/dropdowns/dropdowns.js, library/src/pivotal-ui/components/dropdowns/dropdowns.scss, library/src/pivotal-ui/components/dropdowns/index.js, styleguide/docs/react/dropdowns.js
[#116913731]
BREAKING CHANGE: split prop must be passed in to split the dropdown
label and toggle. Previously, providing a toggle would automatically
split the label and toggle.
Signed-off-by: Elena Sharma <esharma@pivotal.io>
=> feat(dropdowns): React Dropdown does not need a title

library/spec/pivotal-ui-react/dropdown/dropdown-item_spec.js, library/src/pivotal-ui-react/dropdowns/dropdowns.js
We'd like to pass through additional props, such as `target`, to the anchor tag inside of a DropdownItem.
=> feat(DropdownItem): Pass additional props if DropdownItem has an href

library/spec/pivotal-ui-react/table/table_spec.js, library/src/pivotal-ui-react/table/table.js
The table react component seems to add the data props to the table element which results in the table strings being written as data="Object [object] Object [object] Object [object]"
This removes the prop from the table.
=> fix(table): do not allow the data property to be added to the table element itself

library/src/pivotal-ui/components/progress-bars/README.md, library/src/pivotal-ui/components/progress-bars/progress-bars.scss, styleguide/docs/css/progress-bars.scss
- no longer set background color to red when the progress bar reaches 90%
- min-height of progress bar is 10px
- default color of progress bar is $navy-9
=> feature(progress-bars): improve default style

styleguide/docs/css/colors.scss
@pivotal-plech and I worked to remove an inline style on the shadow chips in the color documentation to improve the alignment of this design element. We also changed the background color of the containing div to better illustrate how to use this element.
GitHub Issue #412
=> chore(documentation): align shadow chips

CONTRIBUTING.md, css_critic.sh, styleguide/package.json, styleguide_serve.sh, test.sh, update_styleguide.sh
- Ensure consistent gulp version across machines and CI
- Less onus on users to install global tools
=> Use node_modules gulp instead of global gulp

styleguide/docs/react/table.js
Because.. intellij complains about the one egregious comma :) QOL for people copy-pasting
=> (tiny doc update) trailing comma

library/src/pivotal-ui/components/tables/tables.scss
https://www.pivotaltracker.com/n/projects/1126018/stories/135361221
Not 100% stoked about using position absolute but with any relative positioning I can think of the table header would get moved (since the columns don't have a fixed width). Open to better ideas!
Another thought I had was each column could have that space defined (fixed width) but either empty/not empty. This PRed solution is quite a bit simpler and more intuitive, which is why I went this direction.
Again, open to other ideas.
=> [#135361221] fix weird column resize

library/spec/pivotal-ui-react/buttons/button_spec.js, library/src/pivotal-ui-react/buttons/buttons.js, library/src/pivotal-ui/components/buttons/buttons.scss, styleguide/docs/react/buttons.js
Current API:
```
<DangerButton icon={<Icon src="spinner"/>}>
Link
</DangerButton>
```
Waiting on the **8pt grid story to be finished** before we style (and merge) this.
Also, note that if a user provides an icon with `verticalAlign="baseline"` it'll totally wreck the styling of the icon within the button. We could:
- Ignore their verticalAlign setting inside the `Button` component (basically overwrite it)
- More styling!
=> Feat(Buttons): Add support for button icons

styleguide/docs/css/flex-grids.scss
These examples will help explain this concept better. Currently confusing because the col-grows are too large to visually communicate the concept.
=> Update to flex grow examples

library/spec/pivotal-ui-react/mixins/scrim_mixin_spec.js, library/spec/pivotal-ui-react/modals/modals_spec.js, library/src/pivotal-ui-react/mixins/mixins/scrim_mixin.js, library/src/pivotal-ui-react/modals/modals.js
Fix(Modals, Scrim): do not make direct calls to document
- dependency inject the document function for testability
- works without a document so the component can be server rendered.
Signed-off-by: Weyman Fung <wfung@pivotal.io>
=>  do not make direct calls to document

library/spec/pivotal-ui-react/copy-to-clipboard/copy-to-clipboard_spec.js, library/src/pivotal-ui-react/copy-to-clipboard/copy-to-clipboard.js
- do not default a property that points to window so that the component
can be rendered in a non-browser environment
Signed-off-by: Ryan Dy <rdy@pivotal.io>
=> Fixes(copy-to-clipboard): Fixes calls to window and document

package.json, spec/pivotal-ui-react/select/select_spec.js, spec/pivotal-ui-react/spec_helper.js, src/react/select/select.js, yarn.lock
An `<li>` tag can have a value but it means something different in certain browsers. Use a data-value attribute instead to store that value and call onChange with it separately instead of mutating the target DOM node.
=> Fix bug with select value

spec/pivotal-ui-react/tooltip/tooltip_trigger_spec.js, src/react/tooltip/tooltip.js
Resolves #536.
Adds the ability to manually control the visibility of Tooltips used with the TooltipTrigger, bringing it inline with the functionality of the OverlayTrigger.
=> Allow manual control of TooltipTrigger visibility

spec/pivotal-ui-react/copy-to-clipboard/clipboard-helper_spec.js, spec/pivotal-ui-react/copy-to-clipboard/copy-to-clipboard_spec.js, src/react/copy-to-clipboard/clipboard-helper.js, src/react/copy-to-clipboard/copy-to-clipboard.js
This fixes issue #551. The problem was that we were inserting the text to be copied into a `span` tag, then selecting the `span`'s contents and copying. Since we were copying the rendered HTML content, this meant we lost newlines. I'm using a `textarea` instead of a `span` to preserve the newlines, and I took the opportunity to simplify some of these files. Tested in Chrome (Windows), IE 11, and Edge.
=> Make CopyToClipboard work for text with newlines [#154782444]

src/css/code/code.scss, src/css/pui-variables.scss
This PR adds the standard Mac colors to the close, min, and max terminal buttons (dots) via nth-child selectors.
=> Style Close Min Max Terminal Buttons for Code component

spec/pivotal-ui-react/checkbox-dropdown/checkbox-dropdown_spec.js, src/react/checkbox-dropdown/checkbox-dropdown.js
This is a pull request to make CheckboxDropdown accept initial state for whether a box is checked or not.
The labels prop can now either be an array, like the existing interface, or an object.  If it is an object, the keys are the labels for the checkboxes and the values are booleans representing whether a box is checked or not.
It looks like we changed many tests, but we just had to namespace the different label states, b/c our change was in the constructor.
=> CheckboxDropdown accepts initial state for box checked-ness.

src/css/alerts/alerts.scss
We noticed that the `Alert` component is defined as a flexbox in it's `scss` file, but also has a flexbox grid as it's children. This produced a bug on App SSO, and after discussion with Pivotal UI team, we determined that the behavior was redundant and should be merged.
We experimented by removing the outer flex but this did not work, the `squish` bug still occurred. This change fixes the issue by removing flex on the outer div.
Weird flex but ok. 👌
/cc @jberney
=> Fix nested flex issue on Alerts

spec/pivotal-ui-react/forms/form_spec.js, src/react/forms/form.js
- This allows the user to set any error messages that should appear on
initial render
Signed-off-by: Shaan Sapra <shsapra@pivotal.io>
=> Introduce `setErrors` callback to Form component

spec/pivotal-ui-react/table/plugins/row-drawer_spec.js, src/react/table/plugins/row-drawer.js
- introduce props to get and set the expanded state
- introduce props to set the collapsed and expanded icon
Signed-off-by: Brian Upton <bupton@pivotal.io>
=> Allow the rowDrawer plugin's expanded state to be controlled

docs/components/checkbox-dropdowns.md, spec/react/checkbox-dropdown/checkbox_dropdown.spec.js, src/react/checkbox-dropdown/checkbox_dropdown.js
Metrics would like to use the checkbox dropdown but with a different title. I believe the change is backwards compatible. If there is a better property name to use to prevent the warning from React about not recognizing a prop on a DOM element, please change the name.
=> Make title of checkbox dropdown configurable
